name: Azure Static Web Apps CI/CD (Frontend Only)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/InventoryManagementClient/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'frontend/InventoryManagementClient/**'
  workflow_dispatch:

jobs:
  build_app:
    runs-on: ubuntu-latest
    name: Build Frontend App
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        # This step ensures we use the correct Node.js version for the build.
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
        working-directory: './frontend/InventoryManagementClient'
      - name: Upload artifact for deployment
        # Updated to use v4 of the action.
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-artifact
          path: './frontend/InventoryManagementClient/dist'

  deploy_app:
    needs: build_app
    runs-on: ubuntu-latest
    name: Deploy to Azure
    steps:
      - name: Download build artifact
        # Updated to use v4 of the action.
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-artifact
          path: .
      - name: 'Deploy to Azure Static Web Apps'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_DUNE_03325F203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # By providing a custom app_artifact_location, the action will skip its own build process.
          app_artifact_location: "."
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "" # We don't need app_location because we're providing the artifact directly.
          api_location: ""
          output_location: ""
          ###### End of Repository/Build Configurations ######
